global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-monitor'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093" 

rule_files:
  - 'prometheus.rules.yml' 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['nodeexporter:9100']
